# Generated by Django 2.2.6 on 2019-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Atalho'),
        ),
    ]
